//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime Published { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
