//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit_Cards
    {
        public int CreditId { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string UserMail { get; set; }
    }
}
